[package]
org = "wso2healthcare"
name = "PatientAPI"
version = "0.1.1"
export = ["PatientAPI"]
distribution = "2201.1.2"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Patient","r4","international"]

[build-options]
observabilityIncluded = true
